### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by lxyuma** [raysrashmi/omniauth-foursquare#11]
Hi.
Recently, i update omniauth version. And, I started to use omniauth-foursquare.

mypage can

1. get /auth/foursquare
1. and redirect foursquare authorization page.
1. if I select allow, redirect mypage.

=> next, I have looked this error.

```
Faraday::Error::ConnectionFailed (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed)
```

How can I solve this error?

- I have tried such article(add client_options) but , not work.
  - http://stackoverflow.com/questions/3977303/omniauth-facebook-certificate-verify-failed

- everyone writes, update ruby in rvm and reinstall openssl in rvm, but i don't use rvm

- environment is 
 - CentOS release 5.6 (Final)
 - ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]  it is not rvm. native install
 - 'rails', '3.1.3'

- I have used old omniauth version 0.3.0, and I can login foursquare.if I update this version, It doesnot work.

**Comment by arunagw** [comment]
Please reopen if you still have this issue.
