### ISSUE TITLE
Foursquare API now require a version params

### ISSUE THREAD

**Issue by andreazaupa** [raysrashmi/omniauth-foursquare#14]
Hi! 
I've got this error on the callback_phase

<OAuth2::Error: : 
{"meta":{"code":410,"errorType":"param_error","errorDetail":"The Foursquare API no longer supports requests that do not pass in a version parameter. For more details see https:\/\/developer.foursquare.com\/overview\/versioning"},"response":{}}>

In the Foursquare docs is reported that all requests require a v=YYYYMMDD parameter from date  28-01-2014.

https://developer.foursquare.com/overview/versioning

I will try to make a pull request for this, but I don't have eneugh time at this moment ...

**Comment by arunagw** [comment]
As https://github.com/raysrashmi/omniauth-foursquare/pull/15 is merged. Closing this now.

@andreazaupa please ask again if you still have this issue.
