### ISSUE TITLE
Feature Request: Example use with Devise

### ISSUE THREAD

**Issue by jstart** [raysrashmi/omniauth-foursquare#9]
Do you have this gem working with devise?  I am trying to use the omniauth support with devise, but I am having trouble with the OmniauthCallbacksController.

**Comment by rodrigoargumedo** [comment]
I was able to get this Omniauth-Foursquare gem with Devise working.. I will update with some gist later.

**Comment by arunagw** [comment]
Should we close this?

**Comment by rodrigoargumedo** [comment]
I highly recommend doing so.

**Comment by arunagw** [comment]
thanks
